### ISSUE TITLE
devise_token_auth is not working in rails 6 ruby 2.6

### ISSUE THREAD

**Issue by smitakiran25** [lynndylanhurley/devise_token_auth#1259]
I am using rails 6 and ruby 2.6 and devise 4.6 , i am trying to bundle install devise_token_auth getting following issue 

> $ bundle 
> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
> Fetching gem metadata from https://rubygems.org/.........
> Fetching gem metadata from https://rubygems.org/.
> Resolving dependencies...
> Bundler could not find compatible versions for gem "devise":
>   In snapshot (Gemfile.lock):
>     devise (= 4.6.0)
> 
>   In Gemfile:
>     devise (~> 4.6)
> 
>     devise_token_auth was resolved to 0.1.43.beta1, which depends on
>       devise (> 3.5.2, < 4.4)
> 
> Running `bundle update` will rebuild your snapshot from scratch, using only
> the gems in your Gemfile, which may resolve the conflict.

$ ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]

**Comment by trajkovvlatko** [comment]
Hi, @smitakiran25 
I bumped into the same issue today. Removing Gemfile.lock and running bundle install one again, fixed the issue.
Can you try and see if that helps?

**Comment by bananatron** [comment]
After bundle succeeds, I get `method_missing': undefined method `devise' for User` after upgrading to `1.1.0`. I never did devise install with the previous version and everything was working fine before - does anyone else have this issue?

**Comment by nmacawile** [comment]
I'm also having this issue with `1.1.0` after running `rails db:migrate`.
```
NoMethodError: undefined method `devise' for User (call 'User.connection' to establish a connection):Class
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.6.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/home/ubuntu/workspace/app/models/user.rb:6:in `<class:User>'
/home/ubuntu/workspace/app/models/user.rb:3:in `<top (required)>'
```

**Comment by CDAracena** [comment]
> After bundle succeeds, I get `'method_missing': undefined method 'devise' for User` after upgrading to `1.1.0`. I never did devise install with the previous version and everything was working fine before - does anyone else have this issue?
> 
> Btw, this is what the lockfile defaults for me after removing & rebundling:
> 
> ```
>     devise (4.6.1)
>       bcrypt (~> 3.0)
>       orm_adapter (~> 0.1)
>       railties (>= 4.1.0, < 6.0)
>       responders
>       warden (~> 1.2.3)
>     devise_token_auth (1.1.0)
>       devise (> 3.5.2, < 4.7)
>       rails (>= 4.2.0, < 6)
> ```

I actually have the same issue...has anyone ran into this?

**Comment by bananatron** [comment]
Adding `extend Devise::Models` to your Devise models (`User.rb`) did the trick for me, as mentioned here: https://github.com/lynndylanhurley/devise_token_auth/issues/1276

I'm not sure if this is an issue unique to upgrades, but if not these instructions don't seem to be in the readme 😢 .

**Comment by MaicolBen** [comment]
Closing as it isn't happening to me after upgrading to rails 6, what is still correct the issue about using the generator in #1276

**Comment by onomojo** [comment]
This should be reopened. It doesn't work with a fresh Rails 6 project due to old dependencies. Maybe you should just remove the upper limit restriction on devise:

`
    devise_token_auth (>= 1.1.1) was resolved to 1.1.1, which depends on
      devise (> 3.5.2, < 4.7) was resolved to 3.5.10, which depends on
        railties (>= 3.2.6, < 5)
`

**Comment by onomojo** [comment]
Looks like the gems on rubygems.org are outdated. Master seems to work with Rails 6 but the latest gem fails because its forcing an older devise version.

**Comment by MaicolBen** [comment]
Released 1.1.2!

**Comment by mensaheddy** [comment]
I have had same issue. Here is what i did:

1) Add 'devise_token_auth' gem in the Gemfile.

2) run rails g devise:install

3) run rails generate devise_token_auth:install User auth

4) run rails db:migrate
